# fly.toml app configuration file generated for balancer-apr-db on 2023-11-29T22:47:27-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "balancer-apr-db"
primary_region = "iad"

[env]
  FLY_SCALE_TO_ZERO = "1h"
  PRIMARY_REGION = "iad"

[[mounts]]
  source = "pg_data"
  destination = "/data"
  auto_extend_size_threshold = 0

[[services]]
  protocol = "tcp"
  internal_port = 5432
  auto_start_machines = true

  [[services.ports]]
    port = 5432
    handlers = ["pg_tls"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[[services]]
  protocol = "tcp"
  internal_port = 5433
  auto_start_machines = true

  [[services.ports]]
    port = 5433
    handlers = ["pg_tls"]
  [services.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[checks]
  [checks.pg]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/pg"
  [checks.role]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/role"
  [checks.vm]
    port = 5500
    type = "http"
    interval = "15s"
    timeout = "10s"
    path = "/flycheck/vm"

[[metrics]]
  port = 9187
  path = "/metrics"
