[profile.default]
src = 'src'
out = 'out'
libs = ['lib', '../../lib', 'node_modules']
test = 'test'
solc = '0.7.6'
allow_paths = [
    'lib/balancer-v2-monorepo/',
    'lib/forge-std/',
    'lib/forge-std/lib/ds-test/src/',
    '@balancer-labs/balancer-js/=lib/balancer-v2-monorepo/pkg/balancer-js/',
    '@balancer-labs/v2-deployments/=lib/balancer-v2-monorepo/pkg/deployments/',
    '@balancer-labs/v2-governance-scripts/=lib/balancer-v2-monorepo/pkg/governance-scripts/',
    '@balancer-labs/v2-interfaces/=lib/balancer-v2-monorepo/pkg/interfaces/',
    '@balancer-labs/v2-liquidity-mining/=lib/balancer-v2-monorepo/pkg/liquidity-mining/',
    '@balancer-labs/v2-pool-linear/=lib/balancer-v2-monorepo/pkg/pool-linear/',
    '@balancer-labs/v2-pool-stable/=lib/balancer-v2-monorepo/pkg/pool-stable/',
    '@balancer-labs/v2-pool-utils/=lib/balancer-v2-monorepo/pkg/pool-utils/',
    '@balancer-labs/v2-pool-weighted/=lib/balancer-v2-monorepo/pkg/pool-weighted/',
    '@balancer-labs/v2-solidity-utils/=lib/balancer-v2-monorepo/pkg/solidity-utils/',
    '@balancer-labs/v2-standalone-utils/=lib/balancer-v2-monorepo/pkg/standalone-utils/',
    '@balancer-labs/typechain/=lib/balancer-v2-monorepo/pkg/typechain/',
    '@balancer-labs/v2-helpers/=lib/balancer-v2-monorepo/pvt/helpers/',
    'balancer-v2-monorepo/=lib/balancer-v2-monorepo/',
]

remappings = [
    '@balancer-labs/balancer-js/=lib/balancer-v2-monorepo/pkg/balancer-js/',
    '@balancer-labs/v2-deployments/=lib/balancer-v2-monorepo/pkg/deployments/',
    '@balancer-labs/v2-governance-scripts/=lib/balancer-v2-monorepo/pkg/governance-scripts/',
    '@balancer-labs/v2-interfaces/=lib/balancer-v2-monorepo/pkg/interfaces/',
    '@balancer-labs/v2-liquidity-mining/=lib/balancer-v2-monorepo/pkg/liquidity-mining/',
    '@balancer-labs/v2-pool-linear/=lib/balancer-v2-monorepo/pkg/pool-linear/',
    '@balancer-labs/v2-pool-stable/=lib/balancer-v2-monorepo/pkg/pool-stable/',
    '@balancer-labs/v2-pool-utils/=lib/balancer-v2-monorepo/pkg/pool-utils/',
    '@balancer-labs/v2-pool-weighted/=lib/balancer-v2-monorepo/pkg/pool-weighted/',
    '@balancer-labs/v2-solidity-utils/=lib/balancer-v2-monorepo/pkg/solidity-utils/',
    '@balancer-labs/v2-standalone-utils/=lib/balancer-v2-monorepo/pkg/standalone-utils/',
    '@balancer-labs/typechain/=lib/balancer-v2-monorepo/pkg/typechain/',
    '@balancer-labs/v2-helpers/=lib/balancer-v2-monorepo/pvt/helpers/',
    'balancer-v2-monorepo/=lib/balancer-v2-monorepo/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
    'solmate/=lib/solmate/src/',
]
